title: AWS InsuranceLake
description: Collect, Cleanse, and Consume all your insurance data in one secure and scalable location
remote_theme: tomjoht/documentation-theme-jekyll
plugins:
- jekyll-remote-theme
